# Generated by Django 2.0.3 on 2018-03-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0002_auto_20180308_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gener',
            name='artists',
            field=models.ManyToManyField(to='music_library_app.Artist'),
        ),
    ]
