# Generated by Django 2.0.3 on 2018-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0003_auto_20180308_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gener',
            options={},
        ),
        migrations.AddField(
            model_name='song',
            name='last_play',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
