# Generated by Django 2.0.3 on 2018-03-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0005_auto_20180309_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.DateField(),
        ),
    ]
